// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetSpa.Modules.Operation.Infrastructure.Persistence;

#nullable disable

namespace PetSpa.Modules.Operation.Migrations
{
    [DbContext(typeof(OperationDbContext))]
    partial class OperationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("operation")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetSpa.Modules.Operation.Domain.Entities.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("room_name");

                    b.Property<string>("RoomType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("room_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("AVAILABLE")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("RoomName")
                        .IsUnique();

                    b.ToTable("room", "operation", t =>
                        {
                            t.HasCheckConstraint("ck_room_status", "status IN ('AVAILABLE', 'UNAVAILABLE', 'MAINTENANCE')");
                        });
                });

            modelBuilder.Entity("PetSpa.Modules.Operation.Domain.Entities.ServiceSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingDetailId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_details_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("ExpectedFinishAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_finish_at");

                    b.Property<DateTime?>("ExpectedStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_start_at");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("WAITING")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("BookingDetailId")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.HasIndex("Status");

                    b.ToTable("service_session", "operation", t =>
                        {
                            t.HasCheckConstraint("ck_service_session_actual_time_order", "started_at IS NULL OR finished_at IS NULL OR finished_at >= started_at");

                            t.HasCheckConstraint("ck_service_session_expected_time_order", "expected_start_at IS NULL OR expected_finish_at IS NULL OR expected_finish_at >= expected_start_at");

                            t.HasCheckConstraint("ck_service_session_status", "status IN ('WAITING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("PetSpa.Modules.Operation.Domain.Entities.Staff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("fullname");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<DateOnly?>("HiredDate")
                        .HasColumnType("date")
                        .HasColumnName("hired_date");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("staff", "operation", t =>
                        {
                            t.HasCheckConstraint("ck_staff_gender", "gender IN ('MALE', 'FEMALE', 'OTHER')");

                            t.HasCheckConstraint("ck_staff_role", "role IN ('MANAGER', 'RECEPTIONIST', 'STAFF')");

                            t.HasCheckConstraint("ck_staff_status", "status IN ('ACTIVE', 'INACTIVE')");
                        });
                });

            modelBuilder.Entity("PetSpa.Modules.Operation.Domain.Entities.StaffAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("ServiceSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_session_id");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_id");

                    b.HasKey("Id");

                    b.HasIndex("ServiceSessionId");

                    b.HasIndex("StaffId");

                    b.HasIndex("ServiceSessionId", "StaffId")
                        .IsUnique();

                    b.ToTable("staff_assignment", "operation");
                });

            modelBuilder.Entity("PetSpa.Modules.Operation.Domain.Entities.StaffShift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date")
                        .HasColumnName("shift_date");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("SCHEDULED")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ShiftDate");

                    b.HasIndex("StaffId");

                    b.HasIndex("StaffId", "ShiftDate");

                    b.ToTable("staff_shift", "operation", t =>
                        {
                            t.HasCheckConstraint("ck_staff_shift_status", "status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED')");

                            t.HasCheckConstraint("ck_staff_shift_time_order", "end_time > start_time");
                        });
                });

            modelBuilder.Entity("PetSpa.Modules.Operation.Domain.Entities.ServiceSession", b =>
                {
                    b.HasOne("PetSpa.Modules.Operation.Domain.Entities.Room", "Room")
                        .WithMany("ServiceSessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_session_room");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PetSpa.Modules.Operation.Domain.Entities.StaffAssignment", b =>
                {
                    b.HasOne("PetSpa.Modules.Operation.Domain.Entities.ServiceSession", "ServiceSession")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("ServiceSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_assignment_service_session");

                    b.HasOne("PetSpa.Modules.Operation.Domain.Entities.Staff", "Staff")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_assignment_staff");

                    b.Navigation("ServiceSession");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PetSpa.Modules.Operation.Domain.Entities.StaffShift", b =>
                {
                    b.HasOne("PetSpa.Modules.Operation.Domain.Entities.Staff", "Staff")
                        .WithMany("StaffShifts")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_shift_staff");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PetSpa.Modules.Operation.Domain.Entities.Room", b =>
                {
                    b.Navigation("ServiceSessions");
                });

            modelBuilder.Entity("PetSpa.Modules.Operation.Domain.Entities.ServiceSession", b =>
                {
                    b.Navigation("StaffAssignments");
                });

            modelBuilder.Entity("PetSpa.Modules.Operation.Domain.Entities.Staff", b =>
                {
                    b.Navigation("StaffAssignments");

                    b.Navigation("StaffShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
