<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PetSpa.Modules\Billing\PetSpa.Modules.Billing.csproj" />
    <ProjectReference Include="..\PetSpa.Modules\Booking\PetSpa.Modules.Booking.csproj" />
    <ProjectReference Include="..\PetSpa.Modules\Customer\PetSpa.Modules.Customer.csproj" />
    <ProjectReference Include="..\PetSpa.Modules\Operation\PetSpa.Modules.Operation.csproj" />
    <ProjectReference Include="..\PetSpa.Modules\Resource\PetSpa.Modules.Resource.csproj" />
    <ProjectReference Include="..\PetSpa.SharedKernel\PetSpa.SharedKernel.csproj" />
  </ItemGroup>

</Project>
